name: CI Angular app through Github Actions
on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:


jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3


      - run: npm install --no-audit
      - run: npm run lint:ci

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [ 16, 17 ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - run: npm install --no-audit
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless

  build:
    needs: [ lint, test ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2


      - run: npm install --no-audit
      - run: npm run build:ci -- --output-path=./dist

      - uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: dist


